name: Version & Release

on:
  push:
    branches:
      - master

jobs:
  CheckVersion:
    runs-on: ubuntu-latest
    container:
      image: rightbrainnetworks/auto-semver
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}   # checkout the correct branch name
        fetch-depth: 0                # fetch the whole repo history

    - name: Git Version
      id: version
      uses: codacy/git-version@2.7.1
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.BIO_GITHUB_PAT }}
      with:
        tag_name: latest
        release_name: ${{ steps.version.outputs.version }}
        body: Release Version ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false